[project]
name = "ragdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "faiss-cpu>=1.12.0",
    "langchain>=0.3.27",
    "langchain-community>=0.3.27",
    "langgraph>=0.6.5",
    "pydantic>=2.11.7",
    "pypdf>=6.0.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "streamlit>=1.48.1",
    "wikipedia>=1.4.0",
    "langchain-groq",
    "langchain-huggingface",
    "sentence-transformers",
    "redis>=8.1.0",
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.3",
    "jsonpatch>=1.33",
    "langchain-chroma>=0.2.6",
    "rank-bm25>=0.2.2",
    "mem0ai>=2.0.18",
    "google-genai>=2.18.1",
    "deepeval>=4.2.0",
    "langchain-openai>=0.3.35",
    "nltk>=3.10.3",
]
